# Site settings
title: Relic
email: bellicosedev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simplistic Jekyll theme loosely following Google's Material Design Guidelines
baseurl: "/RelicPreview" # the subpath of your site, e.g. /blog/
url: "https://github.com/BellicoseDev/Relic" # the base hostname & protocol for your site
keywords: "Jekyll, Relic, HTML, CSS, Blog"
twitter_username: bellicosedev
github_username:  bellicosedev

# Build settings
markdown: kramdown

collections:
    collection1:
        title: "Collection 1"
        output: true
    collection2:
        title: "Collection 2"
        output: true
